spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/qonaqzhai/auth/**
              filters:
                - RewritePath=/qonaqzhai/auth(?<segment>/?.*), /api/auth${segment}

            - id: administration
              uri: http://localhost:8080
              predicates:
                - Path=/qonaqzhai/admin/**
              filters:
                - RewritePath=/qonaqzhai/admin(?<segment>/?.*), ${segment}
                - AuthenticationFilter

            - id: event-service
              uri: http://localhost:8082
              predicates:
                - Path=/qonaqzhai/events/**
              filters:
                - RewritePath=/qonaqzhai/events(?<segment>/?.*), /events${segment}
                - AuthenticationFilter
          discovery:
            locator:
              enabled: false

    eureka:
      client:
        enabled: false

auth-service:
  url: http://localhost:8081
