spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: admin-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/admin/**
              filters:
                - RewritePath=/api/admin/(?<segment>.*), /$\{segment}
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
          discovery:
            locator:
              enabled: false

    eureka:
      client:
        enabled: false

    auth-service:
      url: http://localhost:8081/auth
