spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-h2-console
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/qonaqzhai/auth/h2-console/**
              filters:
                - RewritePath=/qonaqzhai/auth/h2-console(?<segment>/?.*), /h2-console${segment}
                - InternalGatewaySignature

            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/qonaqzhai/auth/**
              filters:
                - RewritePath=/qonaqzhai/auth(?<segment>/?.*), /api/auth${segment}
                - InternalGatewaySignature

            - id: administration
              uri: ${ADMIN_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/qonaqzhai/admin/**
              filters:
                - RewritePath=/qonaqzhai/admin(?<segment>/?.*), ${segment}
                - AuthenticationFilter

            - id: event-service-h2-console
              uri: ${EVENT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/qonaqzhai/events/h2-console/**
              filters:
                - RewritePath=/qonaqzhai/events/h2-console(?<segment>/?.*), /h2-console${segment}
                - InternalGatewaySignature

            - id: event-service
              uri: ${EVENT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/qonaqzhai/events/**
              filters:
                - RewritePath=/qonaqzhai/events(?<segment>/?.*), /events${segment}
                - AuthenticationFilter
                - InternalGatewaySignature

            - id: event-service-items
              uri: ${EVENT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/qonaqzhai/items/**
              filters:
                - RewritePath=/qonaqzhai/items(?<segment>/?.*), /items${segment}
                - AuthenticationFilter
                - InternalGatewaySignature
          discovery:
            locator:
              enabled: false

    eureka:
      client:
        enabled: false

auth-service:
  url: ${AUTH_SERVICE_URL:http://localhost:8081}

security:
  internal-gateway:
    enabled: ${INTERNAL_GATEWAY_AUTH_ENABLED:true}
    secret: ${INTERNAL_GATEWAY_SECRET:766SBSZ9soKRmJISfScxyGLDzht}
